package Shapes.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import Shapes.behavior.Canvas__BehaviorDescriptor;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;

public final class PreviewScene_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public PreviewScene_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:812c69fb-b768-42eb-bf7c-d37f605f8bef(Shapes.intentions)", "5918086158154072069"));
  }
  @Override
  public String getPresentation() {
    return "PreviewScene";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new PreviewScene_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Preview Scene";
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      Canvas__BehaviorDescriptor.interpret_id58xh05AV_OP.invoke(node);
    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return PreviewScene_Intention.this;
    }
  }
}
