package Shapes.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myShape__BehaviorDescriptor = new Shape__BehaviorDescriptor();
  private final BHDescriptor myCircle__BehaviorDescriptor = new Circle__BehaviorDescriptor();
  private final BHDescriptor mySquare__BehaviorDescriptor = new Square__BehaviorDescriptor();
  private final BHDescriptor myCanvas__BehaviorDescriptor = new Canvas__BehaviorDescriptor();
  private final BHDescriptor myColorReference__BehaviorDescriptor = new ColorReference__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myCanvas__BehaviorDescriptor;
      case 1:
        return myCircle__BehaviorDescriptor;
      case 2:
        return myColorReference__BehaviorDescriptor;
      case 3:
        return myShape__BehaviorDescriptor;
      case 4:
        return mySquare__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xf718894dfdff459bL, 0x8ddad7868aeb03b3L, 0x1650368a382a2911L), MetaIdFactory.conceptId(0xf718894dfdff459bL, 0x8ddad7868aeb03b3L, 0x1650368a382a28e5L), MetaIdFactory.conceptId(0xf718894dfdff459bL, 0x8ddad7868aeb03b3L, 0x19ac8c402fffc19bL), MetaIdFactory.conceptId(0xf718894dfdff459bL, 0x8ddad7868aeb03b3L, 0x1650368a3829f664L), MetaIdFactory.conceptId(0xf718894dfdff459bL, 0x8ddad7868aeb03b3L, 0x1650368a382a28fbL)).seal();
}
